repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        args: ["--fix"]
        additional_dependencies: ["ruff==0.12.2"]
        language_version: python3.11

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        language_version: python3.11

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
    - id: mypy
      args:
        [
          "--exclude",
          "(__init__.py)$",
          "--strict",
          "--explicit-package-bases",
        ]
      language: system
