repos:
- repo: local
  hooks:
    - id: mypy
      name: mypy (poetry)
      entry: poetry run mypy first_orchard_solver/
      language: system
      types: [python]
      pass_filenames: false

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.291
  hooks:
    - id: ruff
      args: ["--fix"]
      language_version: python3.11

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
      language_version: python3.11

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
    - id: isort
      language_version: python3.11
